### ISSUE TITLE
Missing heating_thresholds

### ISSUE THREAD

**Issue by VartanAhrensKayayan** [oruhnau/when2heat#2]
The script cannot be run since it is missing the heating_thresholds folder and csv. 

I get the following error when running:

heating_thresholds = read.heating_thresholds(input_path)

No such file or directory: 'C:\\Users\\USER\\Documents\\GitHub\\when2heat\\input\\heating_thresholds\\heating_thresholds.csv'

I have successfully installed the CDS API and ran the previous steps. I tried to run the scripts for 2021 and then again for 2018. Neither worked. I assume there is an issue with the pathfinding (the double bars are odd) or a missing file that should be in the repository.

**Comment by Kostrakles** [comment]
Hi, 
I had the same issue while running the script... 
The "heating_thresholds.csv" seems to be missing... Did anyone found a solution to that? 
Or did anyone get some feedback from the developer? 
Thanks!

**Comment by oruhnau** [comment]
Thanks for the message and sorry that I am seeing this only now. I added the missing input file to the repository.
https://github.com/oruhnau/when2heat/commit/95e73c5d9345e4334ad149a373c63a5b0c14a79f
