### ISSUE TITLE
COP-data of floor and radiator heating are swapped

### ISSUE THREAD

**Issue by chris2311esser** [oruhnau/when2heat#3]
Hello,
i've just downloaded the when2heat xlsx and csv File. I've just tested a couple of countries and the COPs of all technologies for radiator heating are higher than for floor heating in the whole time series, which is not intuitive since the heat sink temperature is lower for floor heating. So I think the COP-results for floor and radiator heating are simply swapped. Would you please check this? Thank you

**Comment by oruhnau** [comment]
Thanks for your comment and sorry for the late reply. This has been fixed in our latest update.
https://github.com/oruhnau/when2heat/commit/3f4267afcf19558aa8380668fa4f7110d45ef3d0
